# Generated by Django 3.2.7 on 2022-01-05 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('submissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eval_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('submission_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='submissions.studentsubmit')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('recommendations', models.TextField(blank=True, default='', max_length=1000, null=True)),
                ('page', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('submission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='submissions.studentsubmit')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PF', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('N', models.FloatField(blank=True, default='', null=True)),
                ('evaluator', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('student_submission', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='submissions.studentsubmit')),
            ],
        ),
    ]
