# Generated by Django 3.2.7 on 2022-01-05 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupname', models.CharField(default='', max_length=225)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mem1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mem1', to=settings.AUTH_USER_MODEL)),
                ('mem2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mem2', to=settings.AUTH_USER_MODEL)),
                ('mem3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mem3', to=settings.AUTH_USER_MODEL)),
                ('mem4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mem4', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currentUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
