# Generated by Django 3.2.7 on 2022-01-05 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proposaltitle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Limitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Panel3request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, default='pending', max_length=100, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='panel3name', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Panel2request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, default='pending', max_length=100, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='panel2name', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Panel1request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, default='pending', max_length=100, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='panel1name', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Adviserrequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposedtitle', models.CharField(default=None, max_length=254)),
                ('finaltitle', models.CharField(default=None, max_length=254)),
                ('titledescription', models.TextField(default=None, null=True)),
                ('status', models.CharField(blank=True, default='pending', max_length=100, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advisername', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdviserAndPanelist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('final_title', models.CharField(blank=True, default='', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adviser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adviser', to='register.userprofile')),
                ('panel1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selectpanel1', to='register.userprofile')),
                ('panel2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selectpanel2', to='register.userprofile')),
                ('panel3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selectpanel3', to='register.userprofile')),
                ('proposed_title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proposaltitle.proposetitle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
